# Generated by Django 3.1.6 on 2021-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gametype',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='your moms house', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='number_of_players',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
